app:
  build: .
  command: python app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: docker_mongodb
  environment:
    - MONGO_INITDB_DATABASE=quotes
  volumes:
    - ./init_db.js:/docker-entrypoint-initdb.d/init_db.js:ro
  ports:
    - 27017:27017